# Generated by Django 4.1.3 on 2023-02-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название животного')),
                ('intro', models.CharField(max_length=300, verbose_name='Краткое описание')),
                ('text', models.TextField(verbose_name='Полное описание')),
            ],
        ),
    ]
