# Generated by Django 4.1.3 on 2023-02-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя животного')),
                ('type', models.CharField(max_length=30, verbose_name='Название животного')),
                ('animal_cl', models.CharField(max_length=30, verbose_name='Класс')),
                ('intro', models.CharField(max_length=300, verbose_name='Краткое описание')),
                ('text', models.TextField(verbose_name='Полное описание')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животны',
            },
        ),
        migrations.DeleteModel(
            name='Animals',
        ),
    ]
